coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        informational: true
    patch:
      default:
        target: auto
        threshold: 5%
        informational: true

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  - "src/test/**/*"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/types.ts"
  - "src/app/**/*"
  - "src/data/**/*"
