export {
  canShare,
  createShareUrl,
  getShareablePlatforms,
  openShareWindow,
  share,
  shareFiles,
  shareImage,
  shareText,
  shareToSocialMedia,
  shareUrl,
  shareViaEmail,
} from './share';

export {
  clearClipboard,
  copyHtmlToClipboard,
  copyImageToClipboard,
  copyMultipleFormats,
  copyToClipboard,
  getClipboardPermission,
  getClipboardText,
  hasClipboardText,
  isClipboardReadSupported,
  isClipboardSupported,
  isClipboardWriteSupported,
  isExecCommandSupported,
  isShareFilesSupported,
  isShareSupported,
  readFromClipboard,
  readRichClipboard,
} from './operations';

export {
  useClipboard,
  useClipboardHistory,
  useClipboardSupport,
  useClipboardText,
  useCopyHtml,
  useCopyToClipboard,
  useCopyWithNotification,
  usePasteFromClipboard,
  useShare,
} from './hooks';

export type {
  ClipboardContent,
  ClipboardContentType,
  ClipboardItem,
  ClipboardPermission,
  ClipboardState,
  CopyButtonProps,
  CopyOptions,
  CopyResult,
  PasteOptions,
  ShareData,
  ShareOptions,
  ShareResult,
  UseClipboardOptions,
  UseClipboardReturn,
} from './types';
