'use client';

export {
  getQueryParam,
  hasQueryParam,
  mergeQueryStrings,
  omitQueryParams,
  parseQueryString,
  pickQueryParams,
  removeFromQueryString,
  sortQueryString,
  stringifyQueryString,
  updateQueryString,
} from './query-string';

export {
  buildUrl,
  createSlug,
  ensureTrailingSlash,
  getDirname,
  getFileExtension,
  getFilename,
  getHash,
  getOrigin,
  getPathname,
  getSearch,
  getSearchParams,
  isAbsoluteUrl,
  isExternalUrl,
  isRelativeUrl,
  isSameOrigin,
  joinPaths,
  normalizePath,
  parseUrl,
  removeHash,
  removeSearchParams,
  removeTrailingSlash,
  setHash,
  setSearchParams,
  slugify,
} from './url-utils';

export {
  createMatcher,
  createRoutePattern,
  extractPathSegments,
  generatePath,
  getActiveRouteParams,
  getParentPath,
  getRelativePath,
  isActiveRoute,
  isChildPath,
  matchRoute,
  matchRoutes,
  rankRoute,
  sortRoutesBySpecificity,
} from './route-matching';

export {
  useCampaignParams,
  useCanGoBack,
  useHash,
  useHistoryLength,
  useIsActiveRoute,
  useNavigate,
  usePreserveQueryParams,
  useQueryParam,
  useRouteMatch,
  useScrollRestoration,
  useSearchParamsState,
  useUrlState,
} from './hooks';

export {
  Breadcrumbs,
  BreadcrumbProvider,
  generateBreadcrumbsFromPath,
  getBreadcrumbStructuredData,
  useBreadcrumbs,
  useBreadcrumbsWithHome,
} from './breadcrumbs';

export {
  ExternalLink,
  NavigationProvider,
  NavLink,
  PrefetchLink,
  useBackNavigation,
  useNavigateWithParams,
  useNavigationGuard,
  useNavigationState,
  useRedirect,
  useUnsavedChangesGuard,
} from './navigation';

export type {
  BreadcrumbConfig,
  BreadcrumbItem,
  CampaignParams,
  HistoryEntry,
  InferParamsFromConfig,
  NavigateOptions,
  ParamConfig,
  ParamsConfig,
  ParsedQuery,
  QueryStringOptions,
  RouteConfig,
  RouteGuard,
  RouteMatch,
  RoutePattern,
  RouterState,
  ScrollPosition,
  ScrollRestorationMode,
  SearchParamsState,
  Serializer,
  TrackingConfig,
  UrlParts,
  UseSearchParamsOptions,
} from './types';
