/**
 * Styled Components Theme
 *
 * This theme object provides access to design tokens in styled-components.
 * Values reference CSS custom properties for consistency with the token system.
 */

export const theme = {
  colors: {
    bg: {
      primary: 'var(--color-bg-primary)',
      secondary: 'var(--color-bg-secondary)',
      tertiary: 'var(--color-bg-tertiary)',
      elevated: 'var(--color-bg-elevated)',
      surface: 'var(--color-bg-surface)',
      surfaceHover: 'var(--color-bg-surface-hover)',
      surfaceActive: 'var(--color-bg-surface-active)',
      overlay: 'var(--color-bg-overlay)',
      inverse: 'var(--color-bg-inverse)',
    },
    fg: {
      primary: 'var(--color-fg-primary)',
      secondary: 'var(--color-fg-secondary)',
      tertiary: 'var(--color-fg-tertiary)',
      muted: 'var(--color-fg-muted)',
      inverse: 'var(--color-fg-inverse)',
      brand: 'var(--color-fg-brand)',
      link: 'var(--color-fg-link)',
      linkHover: 'var(--color-fg-link-hover)',
    },
    border: {
      default: 'var(--color-border-default)',
      subtle: 'var(--color-border-subtle)',
      emphasis: 'var(--color-border-emphasis)',
      strong: 'var(--color-border-strong)',
      brand: 'var(--color-border-brand)',
      focus: 'var(--color-border-focus)',
    },
    brand: {
      50: 'var(--color-brand-50)',
      100: 'var(--color-brand-100)',
      200: 'var(--color-brand-200)',
      300: 'var(--color-brand-300)',
      400: 'var(--color-brand-400)',
      500: 'var(--color-brand-500)',
      600: 'var(--color-brand-600)',
      700: 'var(--color-brand-700)',
      800: 'var(--color-brand-800)',
      900: 'var(--color-brand-900)',
    },
    status: {
      info: 'var(--color-status-info)',
      infoBg: 'var(--color-status-info-bg)',
      success: 'var(--color-status-success)',
      successBg: 'var(--color-status-success-bg)',
      warning: 'var(--color-status-warning)',
      warningBg: 'var(--color-status-warning-bg)',
      error: 'var(--color-status-error)',
      errorBg: 'var(--color-status-error-bg)',
    },
    interactive: {
      primary: 'var(--color-interactive-primary)',
      primaryHover: 'var(--color-interactive-primary-hover)',
      primaryActive: 'var(--color-interactive-primary-active)',
      secondary: 'var(--color-interactive-secondary)',
      secondaryHover: 'var(--color-interactive-secondary-hover)',
      secondaryActive: 'var(--color-interactive-secondary-active)',
    },
  },
  fonts: {
    sans: 'var(--font-sans)',
    mono: 'var(--font-mono)',
    display: 'var(--font-display)',
  },
  fontSizes: {
    xs: 'var(--font-size-xs)',
    sm: 'var(--font-size-sm)',
    base: 'var(--font-size-base)',
    lg: 'var(--font-size-lg)',
    xl: 'var(--font-size-xl)',
    '2xl': 'var(--font-size-2xl)',
    '3xl': 'var(--font-size-3xl)',
    '4xl': 'var(--font-size-4xl)',
    '5xl': 'var(--font-size-5xl)',
    '6xl': 'var(--font-size-6xl)',
    '7xl': 'var(--font-size-7xl)',
  },
  fontWeights: {
    normal: 'var(--font-weight-normal)',
    medium: 'var(--font-weight-medium)',
    semibold: 'var(--font-weight-semibold)',
    bold: 'var(--font-weight-bold)',
  },
  lineHeights: {
    none: 'var(--line-height-none)',
    tight: 'var(--line-height-tight)',
    snug: 'var(--line-height-snug)',
    normal: 'var(--line-height-normal)',
    relaxed: 'var(--line-height-relaxed)',
    loose: 'var(--line-height-loose)',
  },
  spacing: {
    0: 'var(--spacing-0)',
    1: 'var(--spacing-1)',
    2: 'var(--spacing-2)',
    3: 'var(--spacing-3)',
    4: 'var(--spacing-4)',
    5: 'var(--spacing-5)',
    6: 'var(--spacing-6)',
    8: 'var(--spacing-8)',
    10: 'var(--spacing-10)',
    12: 'var(--spacing-12)',
    16: 'var(--spacing-16)',
    20: 'var(--spacing-20)',
    24: 'var(--spacing-24)',
    32: 'var(--spacing-32)',
  },
  radii: {
    none: 'var(--radius-none)',
    sm: 'var(--radius-sm)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-xl)',
    '2xl': 'var(--radius-2xl)',
    full: 'var(--radius-full)',
    button: 'var(--radius-button)',
    card: 'var(--radius-card)',
    input: 'var(--radius-input)',
  },
  shadows: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    focus: 'var(--shadow-focus)',
    focusBrand: 'var(--shadow-focus-brand)',
    card: 'var(--shadow-card)',
    cardHover: 'var(--shadow-card-hover)',
    button: 'var(--shadow-button)',
    buttonPrimary: 'var(--shadow-button-primary)',
    buttonPrimaryHover: 'var(--shadow-button-primary-hover)',
    glowBrand: 'var(--shadow-glow-brand)',
  },
  transitions: {
    fast: 'var(--duration-fast) var(--ease-default)',
    normal: 'var(--duration-normal) var(--ease-default)',
    slow: 'var(--duration-slow) var(--ease-default)',
    colors: 'var(--transition-colors)',
    transform: 'var(--transition-transform)',
    all: 'var(--transition-all)',
    interactive: 'var(--transition-interactive)',
    button: 'var(--transition-button)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  containers: {
    sm: 'var(--container-sm)',
    md: 'var(--container-md)',
    lg: 'var(--container-lg)',
    xl: 'var(--container-xl)',
    '2xl': 'var(--container-2xl)',
    '3xl': 'var(--container-3xl)',
    '4xl': 'var(--container-4xl)',
    '5xl': 'var(--container-5xl)',
    '6xl': 'var(--container-6xl)',
    '7xl': 'var(--container-7xl)',
    prose: 'var(--container-prose)',
  },
  zIndices: {
    behind: -1,
    base: 0,
    dropdown: 100,
    sticky: 200,
    overlay: 300,
    modal: 400,
    popover: 500,
    tooltip: 600,
    toast: 700,
  },
} as const;

export type Theme = typeof theme;

export default theme;
